### ISSUE TITLE
USB Power

### ISSUE THREAD

**Issue by CGuasco** [Aus3D/RUMBA32#19]
I would like to prevent the card from being powered by USB.
My printer is always connected to a Raspberry with the Repetier Server always on (connected to multiple printers).
This way the board can never be OFF; more. most important, USB is not enough to power the board with Nextion and continue to go in protect mode and return to 5V, so pwr is flashing.
Usually I use a USB Cable without 5 V, but in this case USB/Serial chip is not powered.
Is it sufficient to eliminate the fuse F3 (I suppose it is the one close to pin 1 of the USB header) there are drawbacks if there is USB connected (USB / Serial U5 chip powered) and card off?
Alternatively bypass D4 or revert it (USB chip powered by the board) and use a special USB cable (without 5V)
(The first option is preferrable)
Tks, Carlo
Tks

**Comment by chrissbarr** [comment]
Hi @CGuasco, sorry for the very late reply.

Any of the methods you propose should work. However, using the cable without 5V will weaken the ESD protection on the board, so I would suggest either removing F3 or D4.
