### ISSUE TITLE
Paypal donation link

### ISSUE THREAD

**Issue by leseaw** [Aus3D/RUMBA32#30]
or how else can I get anything to you? :)

**Comment by chrissbarr** [comment]
Hi @leseaw, that's very kind of you to offer - thanks!

I've set up the following link if you want to make a donation:

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9TH49ER5JUZBW&source=url)

I'll look at fitting it in on the readme when I'm next editing that.

By the way, if you're looking to get any RUMBA32 boards made up soon, I've just added a new revision (V1.1**B**) which has a slight improvement over the V1.1A I released within the last week. Just a heads up as I remember you have manufactured batches in the past.
